//===============Videos=========================================
export const GET_DATA_USER_REQUEST = 'GET_DATA_USER_REQUEST'
export const GET_DATA_USER_SUCCESS = 'GET_DATA_USER_SUCCESS'
export const GET_DATA_USER_FAILURE = 'GET_DATA_USER_FAILURE'

export const DELETE_DATA_USER_REQUEST = 'DELETE_DATA_USER_REQUEST'
export const DELETE_DATA_USER_SUCCESS = 'DELETE_DATA_USER_SUCCESS'
export const DELETE_DATA_USER_FAILURE = 'DELETE_DATA_USER_FAILURE'

export const PUT_DATA_USER_REQUEST = 'PUT_DATA_USER_REQUEST'
export const PUT_DATA_USER_SUCCESS = 'PUT_DATA_USER_SUCCESS'
export const PUT_DATA_USER_FAILURE = 'PUT_DATA_USER_FAILURE'

export const POST_DATA_USER_REQUEST = 'POST_DATA_USER_REQUEST'
export const POST_DATA_USER_SUCCESS = 'POST_DATA_USER_SUCCESS'
export const POST_DATA_USER_FAILURE = 'POST_DATA_USER_FAILURE'
//===============Videos=========================================
export const GET_DATA_USER_EXCLUIDOS_REQUEST = 'GET_DATA_USER_EXCLUIDOS_REQUEST'
export const GET_DATA_USER_EXCLUIDOS_SUCCESS = 'GET_DATA_USER_EXCLUIDOS_SUCCESS'
export const GET_DATA_USER_EXCLUIDOS_FAILURE = 'GET_DATA_USER_EXCLUIDOS_FAILURE'

export const PUT_DATA_USER_EXCLUIDOS_REQUEST = 'PUT_DATA_USER_EXCLUIDOS_REQUEST'
export const PUT_DATA_USER_EXCLUIDOS_SUCCESS = 'PUT_DATA_USER_EXCLUIDOS_SUCCESS'
export const PUT_DATA_USER_EXCLUIDOS_FAILURE = 'PUT_DATA_USER_EXCLUIDOS_FAILURE'

export const DELETE_DATA_USER_EXCLUIDOS_REQUEST = 'DELETE_DATA_USER_EXCLUIDOS_REQUEST'
export const DELETE_DATA_USER_EXCLUIDOS_SUCCESS = 'DELETE_DATA_USER_EXCLUIDOS_SUCCESS'
export const DELETE_DATA_USER_EXCLUIDOS_FAILURE = 'DELETE_DATA_USER_EXCLUIDOS_FAILURE'